version: '3.8'

services:
  db:
    image: postgres:12
    container_name: biblioteca_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./documentacion/estructura_biblioteca.sql:/docker-entrypoint-initdb.d/estructura_biblioteca.sql
    # ports:
    #   - "5432:5432"
    networks:
      - biblioteca_network

  app:
    build: .
    container_name: biblioteca_app
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./Descargas Sistema:/app/Descargas Sistema
    networks:
      - biblioteca_network

volumes:
  postgres_data:

networks:
  biblioteca_network:
    driver: bridge 